# Learning Python From Scratch!
With Chweya Matagaro

Part 2

# NumPy and Pandas
<p>
    Numpy and Pandas are Python libraries that have to be imported:<ul>
        <li><code>import numpy  as np</code>: <code>'np'</code> is a convention and saves us from writing 'numpy' every single time we use a function in the library</li>
        <li><code>import pandas  as pd</code>: <code>'pd'</code> is a convention and saves us from writing 'pandas' every single time we use a function in the library</li>
        </ul>Numpy is a powerful linear algebra library for Python. Almost all of the libraries in the PyData ecosystem (pandas, scipy, scikit-learn, etc.) rely on NumPy as one of their main building blocks.<ul>
    </ul>You can think of pandas as an extremely powerful version of Excel, with a lot more features.</p>
    
https://numpy.org/doc/1.18/numpy-user.pdf    

In [1]:
import numpy as np
import pandas as pd
from scipy import stats
import math

## Numpy Arrays
<p>
    Arrays are basically either vectors or matrices. Vectors are strictly 1-dimensional (1D) arrays and matrices are 2D. But you should note a matrix can still have only one row or one column<ul>
    </ul>We can convert (type cast) a list into a numpy array by using the code:<code>np.array()</code><ul>
    </ul>A matrix when depicted as an numpy array; each row of the matrix is enclosed in square brackets and all square brackets(i.e. rows) are enclosed in a parethesis <code>()</code><ul>
    </ul>We use the following codes to view the attributes of an array:<ul>
    <li><code>.size()</code>: It counts number of elements in an array.</li>
    <li><code>.ndim()</code>: Generates the dimensions of the matrix</li>
    <li><code>.shape()</code>:Generates size of array in each dimension</li>
    <li><code>.dtype()</code>:Generates data type of elements</li>
    </ul>
    </p>

In [2]:
my_list=[1,2,3]
x=np.array(my_list)

print('Object type:',type(my_list), 'Object:', my_list)
print('\n')

print('Object type:',type(x), 'Object:', x)
print('Size:', x.size,'\nDimension:', x.ndim,'\nShape:',x.shape,'\nData Type:', x.dtype)

Object type: <class 'list'> Object: [1, 2, 3]


Object type: <class 'numpy.ndarray'> Object: [1 2 3]
Size: 3 
Dimension: 1 
Shape: (3,) 
Data Type: int32


In [3]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
y=np.array(my_matrix)
print('Object type: ', type(y) ,'\nObject:\n', y)
print('Size:', y.size,'\nDimension:', y.ndim,'\nShape:',y.shape,'\nData Type:', y.dtype)

Object type:  <class 'numpy.ndarray'> 
Object:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Size: 9 
Dimension: 2 
Shape: (3, 3) 
Data Type: int32


## Reshape an Array: <code>.reshape(i,j)</code>
We can reshape an array with <code>n\*m</code> dimensions to have different dimensions of <code>i\*j</code> IFF <code>ij=nm</code>If you want to store such a transformation, you need to assign the resahpe to a variable.

In [4]:
y=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
my_matrix=np.array(y)
print(type(my_matrix),'\n',my_matrix,'\n')


print('.reshape(3,4):\n',my_matrix.reshape(3,4), '\n\n')


print('.reshape(2,6):\n',my_matrix.reshape(2,6), '\n\n')


print('.reshape(6,2):\n',my_matrix.reshape(6,2), '\n\n')

print('.reshape(6,2).transpose():\n',my_matrix.reshape(6,2).transpose(), '\n\n')


print('.reshape(1,12):\n',my_matrix.reshape(1,12), '\n\n')


print('.reshape(12,1):\n',my_matrix.reshape(12,1), '\n\n')


print('.reshape(12,):\n',my_matrix.reshape(12,), '\n\n')


print('.reshape(12,)).transpose():\n',(my_matrix.reshape(12,)).transpose(), '\n\n')

print(type(my_matrix),'\n',my_matrix,'\n')

<class 'numpy.ndarray'> 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

.reshape(3,4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 


.reshape(2,6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 


.reshape(6,2):
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] 


.reshape(6,2).transpose():
 [[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]] 


.reshape(1,12):
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]] 


.reshape(12,1):
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] 


.reshape(12,):
 [ 1  2  3  4  5  6  7  8  9 10 11 12] 


.reshape(12,)).transpose():
 [ 1  2  3  4  5  6  7  8  9 10 11 12] 


<class 'numpy.ndarray'> 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 



### Generate an Array Range <code>np.arange(start,end)</code> & <code>np.arange(start,end,steps)</code>

<code>np.arange(i,j)</code>: Generates values from i (i.e. inclusive of i), incrementing by a value of 1 upto but exclusive of j.

<code>np.arange(i,j,k)</code>: Generates values from i (i.e. inclusive of i), incrementing by a value of k upto but exclusive of j.

In [5]:
print(np.arange(5,10))
print(np.arange(5,10.5))

[5 6 7 8 9]
[ 5.  6.  7.  8.  9. 10.]


In [6]:
print(np.arange(5,21,2))
print(np.arange(5,20.5,3))
print(np.arange(5.5,20.5,3))

[ 5  7  9 11 13 15 17 19]
[ 5.  8. 11. 14. 17. 20.]
[ 5.5  8.5 11.5 14.5 17.5]


### Generate Evenly Spaced Numbers Over an Interval: <code>np.linspace(start, end, k)</code>
<code>np.linspace(n, m, k)</code>: Generates a vector of k equally spaced elements, starting from n upto and including m

In [7]:
np.linspace(2, 50, 9)

array([ 2.,  8., 14., 20., 26., 32., 38., 44., 50.])

### Generate an Array of Zeros, Ones: <code>np.zeros(i)</code>, <code>np.zeros((i,j))</code>, <code>np.ones(i)</code>, <code>np.ones((i,j))</code>

<code>np.zeros(j)</code>: Generates a 1*j matrix of zeroes, i.e a vector.

<code>np.zeros((i,j))</code>: Generates a i*j matrix of zeroes.

<code>np.ones(j)</code>: Generates a 1*j matrix of ones, i.e. a vector.

<code>np.ones((i,j))</code>: Generates a i*j matrix of ones

In [8]:
print(np.zeros(5),'\n')
print(np.zeros((1,5)),'\n')
print(np.zeros((5,1)),'\n')
print(np.zeros((5,2)),'\n')

[0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0.]] 

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]] 

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] 



In [9]:
print(np.ones(5),'\n')
print(np.ones((1,5)),'\n')
print(np.ones((5,1)),'\n')
print(np.ones((5,2)),'\n')

[1. 1. 1. 1. 1.] 

[[1. 1. 1. 1. 1.]] 

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 



### Generate Identity Matrix: <code>np.eye(n)</code>
<p><code>np.eye(n)</code>: Generates an identity Matrix of dimensions n*n, i.e. a square matrix</p>

In [10]:
print(np.eye(1),'\n')
print(np.eye(2),'\n')
print(np.eye(3),'\n')
print(np.eye(4),'\n')

[[1.]] 

[[1. 0.]
 [0. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 



## Arrays of Random Numbers <code>np.random.______()</code>

<code>np.random</code> is a library within the numpy library. We can call functions which generate arrays or random numbers with varying properties, i.e. generated by various dsistributions.<ul>
    </ul>To view the catalog of distributions type the following code: <code>np.random.</code> then press tab.<ul>
    </ul>Once you pick a distribution, for example <code>np.random.rand</code>, you can press shift & tab to read its documentation.
    </p>

In [11]:
#np.random.

### Uniformly Distributed Random Numbers <code>np.random.rand()</code> & <code>np.random.randint()</code>
The following codes assume numbers are uniformly distributed across a specified interval. If the interval is unspecified, then the interval is a default <code>[0,1)</code><ul>
    
<li> <code>np.random.rand(n)</code>: Randomly generates n numbers in the interval <code>[0,1)</code><ul>
    </ul> The output is packed in a 1-D array</li>
<li> <code>np.random.rand(i,j)</code>: Randomly generates i*j numbers in the interval <code>[0,1)</code><ul>
    </ul> The output is packed in a 2-D array, with dimensions i by j</li>
<li> <code>np.random.randint(n,m)</code>: Randomly generates an interger in the interval <code>[n,m)</code> i.e. uniformly distributed across the interval</li>
    <li> <code>np.random.randint(n,m,k)</code>: Randomly generates k intergers in the interval <code>[n,m)</code> i.e. uniformly distributed across the interval<ul>
    </ul> The output is packed in a 1-D array</li>
    <li> <code>np.random.randint(n,m,(i,j))</code>: Randomly generates i*j intergers in the interval <code>[n,m)</code> i.e. uniformly distributed across the interval<ul>
    </ul> The output is packed in a 2-D array, with dimensions i by j</li>
    </ul> You can go further and use the <code>.reshape()</code> to generate an <code>i*j</code> matrix rather than a vector.

In [12]:
np.random.rand(10)

array([0.08930054, 0.32643953, 0.26788516, 0.56712093, 0.023948  ,
       0.51594039, 0.37975222, 0.88133667, 0.63019248, 0.57028647])

In [13]:
np.random.rand(5,3)

array([[0.93543541, 0.44837119, 0.99959363],
       [0.97866657, 0.98355937, 0.16981451],
       [0.17532378, 0.79965069, 0.5512847 ],
       [0.16866908, 0.42760023, 0.79183779],
       [0.86824126, 0.89218057, 0.84559817]])

In [14]:
np.random.randint(0,50)

22

In [15]:
np.random.randint(0,50,10)

array([36, 38,  0, 16, 30, 13, 40, 32, 17, 26])

In [16]:
np.random.randint(0,50,10).reshape(2,5)

array([[ 0, 49, 39, 12, 22],
       [ 2, 47, 17,  1,  0]])

In [17]:
np.random.randint(0,100,(10,10))

array([[76, 35, 44, 81, 45, 92, 29, 20, 34, 55],
       [33, 75, 56, 92, 77, 75,  1, 74, 46, 23],
       [96, 52,  5, 41, 51, 20, 45, 80,  7, 11],
       [98, 89, 22,  7, 23, 51, 35, 11, 98, 37],
       [59, 12, 19, 56, 51, 61, 17, 47, 96, 39],
       [77, 88, 16, 15, 42, 77, 99, 40, 26, 36],
       [ 6, 42, 17, 65, 82, 73, 99, 89, 26, 26],
       [62, 24, 93, 29,  9, 73, 42, 80, 60, 26],
       [28, 74, 24, 29, 92, 42, 44, 64, 62, 40],
       [39, 20, 41, 62,  7, 45, 47, 65, 26, 52]])

In [18]:
np.random.randint(0,5,(10,10))

array([[4, 2, 1, 3, 2, 0, 4, 3, 3, 1],
       [3, 3, 1, 3, 0, 1, 1, 3, 3, 2],
       [2, 3, 4, 1, 3, 0, 2, 2, 4, 4],
       [3, 3, 3, 2, 0, 0, 3, 2, 3, 3],
       [3, 0, 2, 2, 2, 1, 1, 4, 2, 4],
       [4, 4, 0, 2, 0, 1, 1, 4, 2, 2],
       [1, 2, 1, 1, 1, 4, 3, 2, 3, 1],
       [0, 3, 1, 4, 3, 2, 0, 1, 4, 1],
       [0, 4, 2, 3, 1, 0, 0, 1, 1, 2],
       [1, 1, 4, 4, 3, 2, 2, 2, 3, 1]])

### Normal Distributed Random Numbers <code>np.random.rand<bold>n</bold>()</code> & <code>np.random.standard_normal()</code>
The following codes assume numbers are standard normaly distributed, i.e. μ=0 & σ^2=1 </code><ul>
    <li><code>np.random.rand<bold>n</bold>(j)</code>:Outputs j random numbers<ul>
        </ul>Output is a 1-D array, i.e. a vector.</li>
    <li><code>np.random.rand<bold>n</bold>(i,j)</code>:Outputs ,<code>i\*j</code> random numbers<ul>
        </ul>Output is a 2-D array with dimensions i by j, i.e. a vector.</li>
    <li><code>np.random.standard_normal(j)</code>:Outputs j random numbers<ul>
        </ul>Output is a 1-D array, i.e. a vector.</li>
    <li><code>np.random.standard_normal((i,j))</code>:Outputs ,<code>i\*j</code> random numbers<ul>
        </ul>Output is a 2-D array with dimensions i by j, i.e. a matrix.</li>    
    </ul>

The following codes assume numbers are normaly distributed, i.e. μ & σ^2 </code><ul>
    <li><code>np.random.normal(μ,σ)</code>:Outputs a single random number</li>
    <li><code>np.random.normal(μ,σ,k)</code>:Outputs k random number<ul>
        </ul>Output is a 1-D array, i.e. a vector.</li>
    <li><code>np.random.normal(μ,σ,(i,j))</code>:Outputs <code>i\*j</code> random numbers<ul>
        </ul>Output is a 2-D array with dimensions i by j, i.e. a matrix.</li>

In [19]:
#np.random.randn(j)
np.random.randn(5)

array([ 1.16102895, -0.8519907 , -0.12419579, -0.59539592, -0.32676215])

In [20]:
#np.random.randn(j)
np.random.randn(20)

array([ 0.38059953, -0.00474495, -0.70021715, -1.27498278,  0.18979089,
        0.71901493, -1.34453663,  0.340519  , -0.81033651,  0.17077709,
        0.9431612 ,  1.62180125,  0.22087906,  0.29632391,  1.21261746,
       -0.74663114,  0.65654042,  0.3979473 ,  0.42682488, -0.15915259])

In [21]:
#np.random.randn(i,j)
np.random.randn(3,2)

array([[ 0.37811878, -0.58173634],
       [ 1.17706346,  1.36440847],
       [ 0.18554337,  0.59967562]])

In [22]:
#np.random.standard_normal(j)
np.random.standard_normal(20)

array([-0.67364828,  1.05909428,  0.34597703,  0.43622845, -0.58697205,
       -0.92542191, -0.44245128,  0.0041845 , -0.49806572, -0.37324762,
       -0.41766247,  2.29629527,  1.23232804, -0.23708415, -1.10470968,
       -0.49222373,  1.37003723, -0.67901288,  1.60702313, -1.12886082])

In [23]:
#np.random.standard_normal((i,j))
np.random.standard_normal((3,4))

array([[ 0.55541007, -0.31108137,  0.47629189, -1.41359296],
       [ 1.7135972 , -0.37305592,  1.84388833, -0.89023041],
       [ 0.61796145, -1.03771914,  1.54977807, -0.82290389]])

In [24]:
#np.random.normal(μ,σ)
np.random.normal(5,2)

2.687768583614375

In [25]:
#np.random.normal(μ,σ,k)
np.random.normal(5,2,50)

array([4.17424603, 3.85270929, 7.66661928, 6.17523421, 5.89220792,
       3.23549386, 5.80391708, 2.47117778, 3.78333434, 9.09021482,
       2.06855607, 3.95522518, 2.65194049, 3.17311136, 5.78456269,
       8.63145568, 4.02638401, 5.12087571, 6.66564345, 0.9231658 ,
       4.48795392, 5.22331715, 2.78046773, 5.40525819, 3.2009528 ,
       4.96847472, 6.01948739, 6.66009092, 1.53106812, 2.74223127,
       4.62101931, 3.16067752, 3.15539269, 4.25999945, 5.79448059,
       5.86764735, 5.8338208 , 5.12725516, 3.5132802 , 5.40240753,
       6.71410078, 4.94883406, 2.47899847, 4.67940095, 4.14128537,
       3.20726484, 7.45283456, 5.38164433, 3.35628417, 8.80067361])

In [26]:
#np.random.normal(μ,σ,(i,j))
np.random.normal(1,2,(5,5))

array([[ 0.98547583,  1.14243122,  4.71423453,  0.95709334,  0.89842537],
       [-0.2384971 ,  0.29145937, -2.40461761,  4.51766166,  3.8731403 ],
       [ 0.21692373, -0.68088266,  4.40910047, -0.18004905,  2.0475152 ],
       [ 3.31418224,  3.53183631,  5.63135169, -0.0109496 , -0.90088713],
       [ 2.05816953, -0.98199192, -0.07101351, -0.86256593, -1.30459425]])

## Reproducing random numbers using <code>seed()</code>
<p> The <code>seed()</code> allows to generate the same random numbers on Python. 

In [27]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

## max,min,argmax,argmin

We may use the following functions to determine various characteristics of an array 
* <code>.min()</code>: Minimum
* <code>.argmin()</code>: Index of minimum
* <code>.max()</code>: Maximum
* <code>.argmax()</code>: Index of maximum
* <code>.sum()</code>: Sums
* <code>.mean()</code>: Mean/average
* <code>.median()</code>: Median
* <code>.mode()</code>: Mode
* <code>.std()</code>: Standard deviation
* <code>.var()</code>: Variance

In [28]:
np.random.seed(101)
my_matrix=np.array(np.random.randint(0,50,(8,5)))
print(type(my_matrix))
print(my_matrix)

print('Rows:',len(my_matrix))
print('Columns:',len(my_matrix[0]))

my_vector=my_matrix.reshape(len(my_matrix)*len(my_matrix[0]),)
print(my_vector)

my_vector_asc=np.array(sorted(list(my_vector)),)
print(my_vector_asc)
my_matrix_asc=my_vector_asc.reshape(8,5)
print(my_matrix_asc)

<class 'numpy.ndarray'>
[[31 11 17  6 23]
 [11 47  9 13 40]
 [ 4 40 28  0 46]
 [ 5 12 29 40 49]
 [19 47  8 29 34]
 [44  8 19 10 12]
 [31 43 23  0 41]
 [ 9 47  8 36 19]]
Rows: 8
Columns: 5
[31 11 17  6 23 11 47  9 13 40  4 40 28  0 46  5 12 29 40 49 19 47  8 29
 34 44  8 19 10 12 31 43 23  0 41  9 47  8 36 19]
[ 0  0  4  5  6  8  8  8  9  9 10 11 11 12 12 13 17 19 19 19 23 23 28 29
 29 31 31 34 36 40 40 40 41 43 44 46 47 47 47 49]
[[ 0  0  4  5  6]
 [ 8  8  8  9  9]
 [10 11 11 12 12]
 [13 17 19 19 19]
 [23 23 28 29 29]
 [31 31 34 36 40]
 [40 40 41 43 44]
 [46 47 47 47 49]]


In [29]:
np.random.seed(101)
my_matrix=np.array(np.random.randint(0,50,(8,5)))
print(my_matrix)

print('min:', my_matrix.min())
print('min:', np.min(my_matrix))

print('the min is located in index:', my_matrix.argmin())
print('the min is located in index:', np.argmin(my_matrix))

#'axis=0' generates the min for all columns
print('min for all columns:', my_matrix.min(axis=0))
print('min for all columns:', np.min(my_matrix,axis=0))

#'axis=1' generates the min for all columns
print('min for all rows:', my_matrix.min(axis=1))
print('min for all rows:', np.min(my_matrix,axis=1))

[[31 11 17  6 23]
 [11 47  9 13 40]
 [ 4 40 28  0 46]
 [ 5 12 29 40 49]
 [19 47  8 29 34]
 [44  8 19 10 12]
 [31 43 23  0 41]
 [ 9 47  8 36 19]]
min: 0
min: 0
the min is located in index: 13
the min is located in index: 13
min for all columns: [ 4  8  8  0 12]
min for all columns: [ 4  8  8  0 12]
min for all rows: [6 9 0 5 8 8 0 8]
min for all rows: [6 9 0 5 8 8 0 8]


In [30]:
np.random.seed(101)
my_matrix=np.array(np.random.randint(0,50,(8,5)))
print(my_matrix)

print('max:', my_matrix.max())
print('max:', np.max(my_matrix))

print('the max is located in index:', my_matrix.argmax())
print('the max is located in index:', np.argmax(my_matrix))

#'axis=0' generates the max for all columns
print('max for all columns:', my_matrix.max(axis=0))
print('max for all columns:', np.max(my_matrix,axis=0))

#'axis=1' generates the max for all rows
print('max for all rows:', my_matrix.max(axis=1))
print('max for all rows:', np.max(my_matrix,axis=1))

[[31 11 17  6 23]
 [11 47  9 13 40]
 [ 4 40 28  0 46]
 [ 5 12 29 40 49]
 [19 47  8 29 34]
 [44  8 19 10 12]
 [31 43 23  0 41]
 [ 9 47  8 36 19]]
max: 49
max: 49
the max is located in index: 19
the max is located in index: 19
max for all columns: [44 47 29 40 49]
max for all columns: [44 47 29 40 49]
max for all rows: [31 47 46 49 47 44 43 47]
max for all rows: [31 47 46 49 47 44 43 47]


In [31]:
np.random.seed(101)
my_matrix=np.array(np.random.randint(0,50,(8,5)))
print(my_matrix)


print('median:', np.median(my_matrix))


#'axis=0' generates the median for all columns
print('median for all columns:', np.median(my_matrix,axis=0))

#'axis=1' generates the median for all rows
print('median for all rows:', np.median(my_matrix,axis=1))

[[31 11 17  6 23]
 [11 47  9 13 40]
 [ 4 40 28  0 46]
 [ 5 12 29 40 49]
 [19 47  8 29 34]
 [44  8 19 10 12]
 [31 43 23  0 41]
 [ 9 47  8 36 19]]
median: 21.0
median for all columns: [15.  41.5 18.  11.5 37. ]
median for all rows: [17. 13. 28. 29. 29. 12. 31. 19.]


In [32]:
np.random.seed(101)
my_matrix=np.array(np.random.randint(0,50,(8,5)))
print(my_matrix)

print('mean:', my_matrix.mean())
print('mean:', np.mean(my_matrix))

#'axis=0' generates the mean for all columns
print('mean for all columns:', my_matrix.mean(axis=0))
print('mean for all columns:', np.mean(my_matrix,axis=0))

#'axis=1' generates the mean for all rows
print('mean for all rows:', my_matrix.mean(axis=1))
print('mean for all rows:', np.mean(my_matrix,axis=1))

[[31 11 17  6 23]
 [11 47  9 13 40]
 [ 4 40 28  0 46]
 [ 5 12 29 40 49]
 [19 47  8 29 34]
 [44  8 19 10 12]
 [31 43 23  0 41]
 [ 9 47  8 36 19]]
mean: 23.7
mean: 23.7
mean for all columns: [19.25  31.875 17.625 16.75  33.   ]
mean for all columns: [19.25  31.875 17.625 16.75  33.   ]
mean for all rows: [17.6 24.  23.6 27.  27.4 18.6 27.6 23.8]
mean for all rows: [17.6 24.  23.6 27.  27.4 18.6 27.6 23.8]


In [33]:
np.random.seed(101)
my_matrix=np.array(np.random.randint(0,50,(8,5)))
print(my_matrix)

print('sum:', my_matrix.sum())
print('sum:', np.sum(my_matrix))

print('sum:', my_matrix.sum(axis=0))
print('sum:', np.sum(my_matrix,axis=0))

print('sum:', my_matrix.sum(axis=1))
print('sum:', np.sum(my_matrix,axis=1))

[[31 11 17  6 23]
 [11 47  9 13 40]
 [ 4 40 28  0 46]
 [ 5 12 29 40 49]
 [19 47  8 29 34]
 [44  8 19 10 12]
 [31 43 23  0 41]
 [ 9 47  8 36 19]]
sum: 948
sum: 948
sum: [154 255 141 134 264]
sum: [154 255 141 134 264]
sum: [ 88 120 118 135 137  93 138 119]
sum: [ 88 120 118 135 137  93 138 119]


In [34]:
np.random.seed(101)
my_matrix=np.array(np.random.randint(0,50,(8,5)))
print(my_matrix)

print('std:', my_matrix.std())
print('std:', np.std(my_matrix))

print('std:', my_matrix.std(axis=0))
print('std:', np.std(my_matrix,axis=0))

print('std:', my_matrix.std(axis=1))
print('std:', np.std(my_matrix,axis=1))

[[31 11 17  6 23]
 [11 47  9 13 40]
 [ 4 40 28  0 46]
 [ 5 12 29 40 49]
 [19 47  8 29 34]
 [44  8 19 10 12]
 [31 43 23  0 41]
 [ 9 47  8 36 19]]
std: 15.364244205296918
std: 15.364244205296918
std: [13.68164829 16.87036974  8.1230767  14.98957971 12.62933094]
std: [13.68164829 16.87036974  8.1230767  14.98957971 12.62933094]
std: [ 8.8        16.1245155  18.60752536 16.52876281 13.24537655 13.23026833
 15.56406117 15.35447817]
std: [ 8.8        16.1245155  18.60752536 16.52876281 13.24537655 13.23026833
 15.56406117 15.35447817]


When dealing with sample statistics we have to incorporate degrees of freedom. We do this by including the additional argument <code>ddof</code>.

The divisor used in calculationsis <code>n - ddof</code>, where <code>n</code> represents the number of random variables.
By default <code>ddof</code> is zero. Can be used for sample std by using a <code>ddof</code> of 1 thus divisor is <code>(n-1)</code>


In [35]:
np.random.seed(101)
my_matrix=np.array(np.random.randint(0,50,(8,5)))
print(my_matrix)

print('std:', my_matrix.std(ddof=1))
print('std:', np.std(my_matrix,ddof=1))

print('std:', my_matrix.std(axis=0,ddof=1))
print('std:', np.std(my_matrix,axis=0,ddof=1))

print('std:', my_matrix.std(axis=1,ddof=1))
print('std:', np.std(my_matrix,axis=1,ddof=1))

[[31 11 17  6 23]
 [11 47  9 13 40]
 [ 4 40 28  0 46]
 [ 5 12 29 40 49]
 [19 47  8 29 34]
 [44  8 19 10 12]
 [31 43 23  0 41]
 [ 9 47  8 36 19]]
std: 15.559974952191293
std: 15.559974952191293
std: [14.62629726 18.03518387  8.68393426 16.02453476 13.50132269]
std: [14.62629726 18.03518387  8.68393426 16.02453476 13.50132269]
std: [ 9.8386991  18.02775638 20.8038458  18.47971861 14.80878118 14.79188967
 17.40114939 17.16682848]
std: [ 9.8386991  18.02775638 20.8038458  18.47971861 14.80878118 14.79188967
 17.40114939 17.16682848]


In [36]:
np.random.seed(101)
my_matrix=np.array(np.random.randint(0,50,(8,5)))
print(my_matrix)

print('var:', my_matrix.var())
print('var:', np.var(my_matrix))

print('var:', my_matrix.var(axis=0))
print('var:', np.var(my_matrix,axis=0))

print('var:', my_matrix.var(axis=1))
print('var:', np.var(my_matrix,axis=1))

[[31 11 17  6 23]
 [11 47  9 13 40]
 [ 4 40 28  0 46]
 [ 5 12 29 40 49]
 [19 47  8 29 34]
 [44  8 19 10 12]
 [31 43 23  0 41]
 [ 9 47  8 36 19]]
var: 236.05999999999995
var: 236.05999999999995
var: [187.1875   284.609375  65.984375 224.6875   159.5     ]
var: [187.1875   284.609375  65.984375 224.6875   159.5     ]
var: [ 77.44 260.   346.24 273.2  175.44 175.04 242.24 235.76]
var: [ 77.44 260.   346.24 273.2  175.44 175.04 242.24 235.76]


In [37]:
np.random.seed(101)
my_matrix=np.array(np.random.randint(0,50,(8,5)))
print(my_matrix)


#'ddof' Means Delta Degrees of Freedom.
#The divisor used in calculationsis 'n - ddof', where 'n' represents the number of elements.
#By default `ddof` is zero. Can be used for sample std by using a ddof of 1 thus divisor is (n-1)

print('var:', my_matrix.var(ddof=1))
print('var:', np.var(my_matrix,ddof=1))

print('var:', my_matrix.var(axis=0,ddof=1))
print('var:', np.var(my_matrix,axis=0,ddof=1))

print('var:', my_matrix.var(axis=1,ddof=1))
print('var:', np.var(my_matrix,axis=1,ddof=1))

[[31 11 17  6 23]
 [11 47  9 13 40]
 [ 4 40 28  0 46]
 [ 5 12 29 40 49]
 [19 47  8 29 34]
 [44  8 19 10 12]
 [31 43 23  0 41]
 [ 9 47  8 36 19]]
var: 242.11282051282046
var: 242.11282051282046
var: [213.92857143 325.26785714  75.41071429 256.78571429 182.28571429]
var: [213.92857143 325.26785714  75.41071429 256.78571429 182.28571429]
var: [ 96.8 325.  432.8 341.5 219.3 218.8 302.8 294.7]
var: [ 96.8 325.  432.8 341.5 219.3 218.8 302.8 294.7]


In [38]:
#print('mode:', my_matrix.mode())
np.random.seed(101)
my_matrix=np.array(np.random.randint(0,50,(8,5)))

print(my_matrix_asc,'\n')
print(my_matrix_asc.transpose(),'\n')
print(my_vector_asc,'\n')

print('mode:', stats.mode(my_matrix_asc, axis=None),'\n')
print('mode:', stats.mode(my_vector_asc),'\n')

print('mode:', stats.mode(my_matrix_asc,axis=0),'\n')


print('mode:', stats.mode(my_matrix_asc,axis=1))

[[ 0  0  4  5  6]
 [ 8  8  8  9  9]
 [10 11 11 12 12]
 [13 17 19 19 19]
 [23 23 28 29 29]
 [31 31 34 36 40]
 [40 40 41 43 44]
 [46 47 47 47 49]] 

[[ 0  8 10 13 23 31 40 46]
 [ 0  8 11 17 23 31 40 47]
 [ 4  8 11 19 28 34 41 47]
 [ 5  9 12 19 29 36 43 47]
 [ 6  9 12 19 29 40 44 49]] 

[ 0  0  4  5  6  8  8  8  9  9 10 11 11 12 12 13 17 19 19 19 23 23 28 29
 29 31 31 34 36 40 40 40 41 43 44 46 47 47 47 49] 

mode: ModeResult(mode=array([8]), count=array([3])) 

mode: ModeResult(mode=array([8]), count=array([3])) 

mode: ModeResult(mode=array([[0, 0, 4, 5, 6]]), count=array([[1, 1, 1, 1, 1]])) 

mode: ModeResult(mode=array([[ 0],
       [ 8],
       [11],
       [19],
       [23],
       [31],
       [40],
       [47]]), count=array([[2],
       [3],
       [2],
       [3],
       [2],
       [2],
       [2],
       [3]]))


## Array Indexing
<p>
    <code>my_matrix[i]</code> Generates the 'i+1' row, i.e. occupying index i if a matrix, generates the ith index if a vector<ul>
</ul><code>my_matrix[:,j]</code> Generates the 'j+1' column, i.e. occupying column index j if a matrix<ul>
</ul><code>my_matrix[i,j]</code> or <code>my_matrix[i][j]</code>: Generate the elelemnt in row i and column j.<ul>
</ul></p>        

In [39]:
my_vector=np.arange(0,24)
my_matrix=np.arange(0,24).reshape(6,4)
print(my_vector,'\n\n')
print(my_matrix)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [40]:
print(my_vector[0])
print(my_vector[8])
print(my_vector[15])

0
8
15


In [41]:
print(my_matrix[0])
print(my_matrix[1])
print(my_matrix[5])

[0 1 2 3]
[4 5 6 7]
[20 21 22 23]


In [42]:
print(my_matrix[:,0])
print(my_matrix[:,1])
print(my_matrix[:,3])

[ 0  4  8 12 16 20]
[ 1  5  9 13 17 21]
[ 3  7 11 15 19 23]


In [43]:
print(my_matrix[0,0])
print(my_matrix[1,2])
print(my_matrix[3,3])
print(my_matrix[5,3])

0
6
15
23


## Array Slicing
<p> It is quite similar to slicing lists, tuples and strings. For a refresher head into part 1 of 'Learning Python From Scratch!'<ul>
    </ul> The following code demonstrates how to slice vectors and matrices.
    </p>

In [44]:
my_vector=np.arange(0,24)
my_matrix=np.arange(0,24).reshape(6,4)
print(my_vector,'\n\n')
print(my_matrix)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [45]:
print(my_vector[10:], '\n')
print(my_vector[:10], '\n')
print(my_vector[1:5])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23] 

[0 1 2 3 4 5 6 7 8 9] 

[1 2 3 4]


In [46]:
print(my_matrix, '\n')

print(my_matrix[3:], '\n')
print(my_matrix[:2], '\n')
print(my_matrix[1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[0 1 2 3]
 [4 5 6 7]] 

[[ 4  5  6  7]
 [ 8  9 10 11]]


In [47]:
print(my_matrix, '\n')

print(my_matrix[:,2:], '\n')
print(my_matrix[:,:2], '\n')
print(my_matrix[:,1:5])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]
 [22 23]] 

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]
 [16 17]
 [20 21]] 

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]
 [17 18 19]
 [21 22 23]]


In [48]:
print(my_matrix, '\n')

print(my_matrix[3:,2:], '\n')
print(my_matrix[3:,:2], '\n')
print(my_matrix[3:,1:5])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[14 15]
 [18 19]
 [22 23]] 

[[12 13]
 [16 17]
 [20 21]] 

[[13 14 15]
 [17 18 19]
 [21 22 23]]


In [49]:
print(my_matrix, '\n')

print(my_matrix[:2,2:], '\n')
print(my_matrix[:2,:2], '\n')
print(my_matrix[:2,1:5])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[2 3]
 [6 7]] 

[[0 1]
 [4 5]] 

[[1 2 3]
 [5 6 7]]


In [50]:
print(my_matrix, '\n')

print(my_matrix[1:3,2:], '\n')
print(my_matrix[1:3,:2], '\n')
print(my_matrix[1:3,1:5])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[ 6  7]
 [10 11]] 

[[4 5]
 [8 9]] 

[[ 5  6  7]
 [ 9 10 11]]


## Concatenate

In [51]:
my_vector1=np.arange(0,12)
my_matrix1=my_vector1.reshape(4,3)

print(my_vector1,'\n')
print(my_matrix1)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [52]:
np.concatenate([my_vector1,my_vector1])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11])

In [53]:
np.concatenate([my_matrix1,my_matrix1])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

We can add the argument <code>axis</code> if we want to specify whether the concatenation adds along rows or columns:
* <code>axis=0<\code>: The default, adds as additional rows
* <code>axis=1<\code>: Adds as additional columns

In [54]:
np.concatenate([my_matrix1,my_matrix1],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
np.concatenate([my_matrix1,my_matrix1],axis=1)

array([[ 0,  1,  2,  0,  1,  2],
       [ 3,  4,  5,  3,  4,  5],
       [ 6,  7,  8,  6,  7,  8],
       [ 9, 10, 11,  9, 10, 11]])

## Splitting an Array
### Splitting Vectors

In [56]:
my_vector=np.arange(0,24)
my_matrix=np.arange(0,24).reshape(6,4)
print(my_vector,'\n\n')
print(my_matrix)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [57]:
np.split(my_vector, 2)

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

In [58]:
np.split(my_vector, 3)

[array([0, 1, 2, 3, 4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20, 21, 22, 23])]

In [59]:
np.split(my_vector, 4)

[array([0, 1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17]),
 array([18, 19, 20, 21, 22, 23])]

Running this code generates an error: <code>np.split(my_vector, 5)</code>

A work around is <code>np.array_split()</code>:

In [60]:
np.array_split(my_vector, 5)

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19]),
 array([20, 21, 22, 23])]

In [61]:
np.array_split(my_vector, [2,5,15])

[array([0, 1]),
 array([2, 3, 4]),
 array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19, 20, 21, 22, 23])]

### Splitting Matrix
#### By Rows

In [62]:
np.split(my_matrix, 2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [63]:
np.split(my_matrix, 3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [64]:
np.vsplit(my_matrix, 2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [65]:
np.vsplit(my_matrix, 3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

#### By Columns

In [66]:
np.split(my_matrix, 2,axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

Running this code generates an error: <code>codenp.split(my_matrix, 3,axis=1)</code>

A work around is <code>np.array_split(,axis=1)</code>

In [67]:
np.array_split(my_matrix, 3,axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18],
        [22]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19],
        [23]])]

In [68]:
np.split(my_matrix, 4,axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16],
        [20]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17],
        [21]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18],
        [22]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19],
        [23]])]

In [69]:
np.hsplit(my_matrix, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

## Array Broadcasting
<p> Brodcasting allows us to assign a value to all elements in a slice</p>

In [70]:
my_vector=np.arange(0,24)
my_matrix=np.arange(0,24).reshape(6,4)

print(my_vector)
print('\n\n')                          #Generates spaces
print(my_matrix)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [71]:
my_vector=np.arange(0,24)

print(my_vector)
print(my_vector[5:11],'\n')

my_vector[5:11]=7

print(my_vector)
print(my_vector[5:11],)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 5  6  7  8  9 10] 

[ 0  1  2  3  4  7  7  7  7  7  7 11 12 13 14 15 16 17 18 19 20 21 22 23]
[7 7 7 7 7 7]


In [72]:
#Assigning a slice to an object and broadcasting that object will also affect the source array:
my_vector=np.arange(0,24)

my_vector_slice=my_vector[5:11]
my_vector_slice[:]=8

print(my_vector)
print(my_vector[5:11],'\n')

[ 0  1  2  3  4  8  8  8  8  8  8 11 12 13 14 15 16 17 18 19 20 21 22 23]
[8 8 8 8 8 8] 



In [73]:
my_vector=np.arange(0,24)
my_vector_copy=my_vector

print(my_vector)
print(my_vector_copy,'\n')

my_vector[8]=999
my_vector_copy[11]=333
print(my_vector)
print(my_vector_copy,'\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 

[  0   1   2   3   4   5   6   7 999   9  10 333  12  13  14  15  16  17
  18  19  20  21  22  23]
[  0   1   2   3   4   5   6   7 999   9  10 333  12  13  14  15  16  17
  18  19  20  21  22  23] 



In [74]:
#If we don't want to affect the source array, we will use the '.copy()' function
#To copy an array independent from the source:
my_vector=np.arange(0,24)
my_vector_copy=my_vector.copy()

print(my_vector)
print(my_vector_copy,'\n')

my_vector[8]=999
my_vector_copy[11]=333
print(my_vector)
print(my_vector_copy)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 

[  0   1   2   3   4   5   6   7 999   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23]
[  0   1   2   3   4   5   6   7   8   9  10 333  12  13  14  15  16  17
  18  19  20  21  22  23]


In [75]:
#To copy a slice independent from the source:
my_vector=np.arange(0,24)
my_vector_slice=my_vector[5:11].copy()

print(my_vector)
print(my_vector[5:11],'\n')
print(my_vector_slice,'\n')

my_vector[5:11]=8
my_vector_slice[:]=3

print(my_vector)
print(my_vector[5:11],'\n')
print(my_vector_slice,'\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 5  6  7  8  9 10] 

[ 5  6  7  8  9 10] 

[ 0  1  2  3  4  8  8  8  8  8  8 11 12 13 14 15 16 17 18 19 20 21 22 23]
[8 8 8 8 8 8] 

[3 3 3 3 3 3] 



In [76]:
my_matrix=np.arange(0,24).reshape(6,4)
print(my_matrix, '\n')
print(my_matrix[1:3,1:5], '\n', '\n')

my_matrix[1:3,1:5]=8

print(my_matrix, '\n')
print(my_matrix[1:3,1:5], '\n', '\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[ 5  6  7]
 [ 9 10 11]] 
 

[[ 0  1  2  3]
 [ 4  8  8  8]
 [ 8  8  8  8]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[8 8 8]
 [8 8 8]] 
 



## Array Boolean Tests & Conditional Selection

In [77]:
my_vector=np.arange(0,26,2)
print(my_vector)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24]


In [78]:
#The code outputs an array indicating which parts of the array generate a 'True' statement
#You can also assign it to a variable
my_vector>10

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True])

In [79]:
#The code can be inserted back into the array to generate only the elements that are 'True'
my_vector[my_vector>10]

array([12, 14, 16, 18, 20, 22, 24])

## Numpy Operations

In [80]:
my_vector=np.arange(0,21)
print(my_vector)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [81]:
print(my_vector+my_vector)
print(my_vector+100)

print('\n')

print(my_vector.sum())                        #'.sum()'Adds up all elements of an array

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120]


210


In [82]:
print(my_vector-my_vector)
print(my_vector-3)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[-3 -2 -1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [83]:
print(my_vector*my_vector)
print(my_vector*3)

[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289
 324 361 400]
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60]


In [84]:
# Warning on division by zero, but not an error!
# Just replaced with nan or inf where applicable
print(my_vector/my_vector)
print(my_vector/3)
print(3/my_vector)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.         4.33333333 4.66666667 5.         5.33333333 5.66666667
 6.         6.33333333 6.66666667]
[       inf 3.         1.5        1.         0.75       0.6
 0.5        0.42857143 0.375      0.33333333 0.3        0.27272727
 0.25       0.23076923 0.21428571 0.2        0.1875     0.17647059
 0.16666667 0.15789474 0.15      ]


C:\Users\user\AppData\Local\Temp\ipykernel_15992\1928371468.py:3: RuntimeWarning: invalid value encountered in true_divide
  print(my_vector/my_vector)
C:\Users\user\AppData\Local\Temp\ipykernel_15992\1928371468.py:5: RuntimeWarning: divide by zero encountered in true_divide
  print(3/my_vector)


In [85]:
print(my_vector**2)
print(my_vector**3)

[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289
 324 361 400]
[   0    1    8   27   64  125  216  343  512  729 1000 1331 1728 2197
 2744 3375 4096 4913 5832 6859 8000]


In [86]:
print(np.power(my_vector,2))
print(np.power(my_vector,3))

[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289
 324 361 400]
[   0    1    8   27   64  125  216  343  512  729 1000 1331 1728 2197
 2744 3375 4096 4913 5832 6859 8000]


In [87]:
print(my_vector)
print(2**my_vector)
print(3**my_vector)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[      1       2       4       8      16      32      64     128     256
     512    1024    2048    4096    8192   16384   32768   65536  131072
  262144  524288 1048576]
[         1          3          9         27         81        243
        729       2187       6561      19683      59049     177147
     531441    1594323    4782969   14348907   43046721  129140163
  387420489 1162261467 -808182895]


In [88]:
print(my_vector)
print(np.power(2,my_vector))
print(np.power(3,my_vector))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[      1       2       4       8      16      32      64     128     256
     512    1024    2048    4096    8192   16384   32768   65536  131072
  262144  524288 1048576]
[         1          3          9         27         81        243
        729       2187       6561      19683      59049     177147
     531441    1594323    4782969   14348907   43046721  129140163
  387420489 1162261467 -808182895]


## Universal Array Functions
Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array.


In [89]:
my_vector=np.arange(0,21)
print(my_vector)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [90]:
np.sqrt(my_vector)       #Square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [91]:
np.exp(my_vector)         #exponential (e^)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [92]:
np.power(my_vector,2)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400], dtype=int32)

In [93]:
np.power(2,my_vector)

array([      1,       2,       4,       8,      16,      32,      64,
           128,     256,     512,    1024,    2048,    4096,    8192,
         16384,   32768,   65536,  131072,  262144,  524288, 1048576],
      dtype=int32)

In [94]:
2**my_vector

array([      1,       2,       4,       8,      16,      32,      64,
           128,     256,     512,    1024,    2048,    4096,    8192,
         16384,   32768,   65536,  131072,  262144,  524288, 1048576],
      dtype=int32)

In [95]:
my_vector**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400], dtype=int32)

In [96]:
np.sin(my_vector)         #sin ()

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525])

In [97]:
np.log(my_vector)            #log ()

C:\Users\user\AppData\Local\Temp\ipykernel_15992\3243936342.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(my_vector)            #log ()


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227])

In [98]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])
a*b

array([0, 0, 0, 0, 0])

In [99]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [100]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])

In [101]:
np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [102]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

In [103]:
A=np.array([[1,2],[3,4],[5,6],[7,8]])
A.transpose()

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])